### ISSUE TITLE
Install GUI on Linux

### ISSUE THREAD

**Issue by danieleceUL** [OlivervZ11/NSSFR-GUI#1]
Hi Oliver:-

I would like to ask whether it would be possible to install this GUI on linux. I have installed MATLAB there.

Best Regards,
Daniel Jakab,

**Comment by OlivervZ11** [comment]
Hi Daniel,

I have not tried it for Linux, I have only exported and tested the GUI on Windows and MacOS. Please try and install the GUI on Linux, but if it does not install, the MATLAB code should work. 

Hope this helps,
Oliver
