### ISSUE TITLE
Can't read in PNG to TIF converted files

### ISSUE THREAD

**Issue by danieleceUL** [OlivervZ11/NSSFR-GUI#2]
Hi Oliver:-

I tried reading in TIF files which were converted from PNG into the GUI however, these files were not read in.
I am aware that your GUI is asking for RAW files not PNG/JPEG ones.
Would there be any way to fix this issue?

Best Regards,
Daniel Jakab,

**Comment by danieleceUL** [comment]
Just to add, the GUI is stuck in a 'processing...' status if I try to read in a folder containing only one TIF image.
How long should a process like this take to complete?

Best Regards,
Daniel Jakab,

**Comment by OlivervZ11** [comment]
Hi Daniel, 
Ensure that it is .tif (lower case, shouldn’t make a difference, but might). 
in terms of time, there are a number of factors. Which Action have you chose? The power of your pc, the OS you are using, GUI or MATLAB code etc. 
I’ve received a email from your tutor. We can organise a meeting to try debug this. 
All the best,
Oliver

**Comment by danieleceUL** [comment]
Hi Oliver:-

Thank you for getting back to me :-)
This is excellent news! Any help from you would be invaluable!

Initially I used Linux Ubuntu 18.04 for running the MATLAB scripts. I also tried installing your GUI on my Windows 10. I try reading in just one '.tif' file in a folder and it seems to enter into a never ending state of 'Processing...' when I choose either options on the GUI. But, it could be that the nature of the PNG to TIF conversion doesn't work. Which is why I went to modify the Part 1 file to read in PNG files as well. Adding this I was able to generate the 'eSFR_Estimation.mat' file using both '.m' scripts.

Running the .m scripts give no issues thankfully :-) it's just when we try to read in the results directly into the GUI i.e. choosing the directory where 'eSFR_Estimation.mat' is located: the GUI (on windows) doesn't respond.

Hopefully, we can get this or the old GUI to work.

For the time being I went back to your old GUI (as this can be edited directly) in the original NS-SFR repo to make something work. Despite using the .m files (with slight modifications) for reading in the PNG files I wasn't able to load the measurements/results into the GUI to view the graphs. Also we can notice significant differences in structure comparing the resulting 'eSFR_Estimation.mat' files generated by both the old and new versions of the .m scripts in both repositories.

I will keep both versions separate from each other.
I will try to get something to work before we meet. Wish me luck! :-)

Best Regards,
Daniel Jakab,

**Comment by OlivervZ11** [comment]
We can discuss these points. 
The old and new codes are not interchangeable, there have been significant changes in the optimisation of the code. 
I’ll have a look at the images you are trying to process during our meeting. 
I could also update the GUI to accept PNGs, this can also be something to discuss.

**Comment by OlivervZ11** [comment]
Also, have you tried the MATLAB code from the new code (rather than the GUI)? The results from this should be read by the GUI. 
All the best,
Oliver

**Comment by danieleceUL** [comment]
Hi Oliver:-

I remember trying this yesterday.
It seems that the GUI doesn't respond to the directory the 'eSFR_Estimation.mat' file is in.

Best Regards,
Daniel Jakab,
